config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about', as: :about
  resources :reviews, only: [:new, :index, :show, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
  end

  def index
    @review = Review.new
    @reviews = Review.all
  end

  def show
  end

  def edit
  end

  def create
    review = Review.new(review_params)
    review.save
    redirect_to review_path(review.id)
  end


  private
  def review_params
    params.require(:review).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/homes/about.html.erb
<!DOCTYPE HTML>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Best Paw</title>
    <link rel="stylesheet" href="/app/assets/styleshhets/homes.scss" />
  </head>
  <body>
    <p>このサイトについての説明</p>
  </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE HTML>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Best Paw</title>
    <link rel="stylesheet" href="/app/assets/styleshhets/homes.scss" />
  </head>
  <body>
    <a href="">肉球画像（予定）</a>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestPaw</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "about", about_path, class: 'nav-link text-dark' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'レビュー投稿', new_reviwe_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<% @reviews.each do |breview| %>
  <%= review.title %>
  <%= review.body %>
  <%= link_to "Show", review_path(review.id) %>
  <%= link_to "Edit", edit_review_path(review.id) %>
  <%= link_to "Destroy", review_path(review.id), method: :delete, "data-confirm" => "Are you sure ?" %>
<% end %>

<%= form_with model: @reviews do |f| %>
  <h6>Title</h6>
    <%= f.text_field :title %>
  <h6>Body</h6>
    <%= f.text_area :body %>
    <%= f.submit 'Create Review' %>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>